# Nixpacks configuration for Railway
# This tells Railway exactly what to install and how

[start]
cmd = "uvicorn web_api:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.setup]
nixPkgs = ["python311", "pip"]
