# Railway configuration for Groq-powered deployment
# Clean, simple FastAPI deployment

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30  # Much faster now!
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
