# Railway Deployment Configuration
# This file tells Railway how to deploy your application

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn web_api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
# Optimize build for Railway
pythonVersion = "3.11"
