# Railway configuration for all-in-one deployment
# Use Docker instead of Nixpacks for Ollama inclusion

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.allinone"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 600  # Longer timeout for model loading
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
